
language: node_js


node_js:
    - '6'
    - '7'


install:
    - npm install -q


script:
    - npm test -- -R dot


branches:
    except:
        - gh-pages


git:
    depth: 9


cache:
    directories:
        - node_modules


dist: trusty
sudo: false

